version: '3.8'

services:
  # The Database (Postgres)
  db:
    image: postgres:15
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: chatapp_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The GUI (Adminer)
  adminer:
    image: adminer
    container_name: chat_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data: